# Generated by Django 3.2.9 on 2021-11-20 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_main',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
