# Generated by Django 3.2.9 on 2021-11-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211123_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='color',
            new_name='color_var',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='size',
            new_name='size_var',
        ),
    ]
